---
- hosts: localhost
  connection: local
  become: "yes"
  remote_user: "{{ server_user.name }}"
  vars_files:
    - ./secrets.yml

  pre_tasks:
    - name: Passwordless users
      become: "yes"
      lineinfile:
        path: /etc/sudoers
        regexp: '\%sudo.+ALL=\(ALL:ALL\).+ALL'
        line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL"
        state: present
      tags: sudoer

  roles:
    - role: basic_setup
      user: "{{ server_user }}"
      tags: basic

    - role: haelle.vimrc
      become_user: "{{ server_user.name }}"
      tags: vim

    - role: haelle.oh_my_zsh
      users:
        - "{{ server_user.name }}"
      tags: zsh

    - role: desktop
      tags: desktop

  # Install desktop packages
  # check docker installation for x86_64
  # ruby
  # nodejs
  # redis
  # python
  # ^ all in docker ? why not

# Gnome plugins:
#  Alt Tab Workspace: https://extensions.gnome.org/extension/310/alt-tab-workspace/
#  Dash to Dock: https://micheleg.github.io/dash-to-dock/
#  system-monitor: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet
#  Pomodoro : https://github.com/codito/gnome-pomodoro/
#  Docker : https://extensions.gnome.org/extension/1065/docker-status/
#  Docker : https://extensions.gnome.org/extension/2224/easy-docker-containers/ (Gnome trop récent demandé)
#  Emoji selector : https://github.com/maoschanz/emoji-selector-for-gnome
