---
# change ansible.cfg ask_pass to true is needed
- hosts: raspberry-lutece
  become: true
  remote_user: "{{ default_user }}"
  gather_facts: "no"
  vars_files:
    - ./secrets.yml

  pre_tasks:
    - local_action: command ssh -o PreferredAuthentications=password -o PubkeyAuthentication=no {{ default_user }}@{{ ansible_host }} "echo success"
      register: default_connection_attempt
      ignore_errors: "yes"

    - set_fact:
        default_connection_failed: "{{ default_connection_attempt.rc != 0 }}"

    - debug:
        msg: "Default connection for {{ ansible_host }} disabled ? {{ default_connection_failed }}"

  roles:
    - role: create_ssh_user
      users:
        - "{{ server_user }}"
      tags: user
      when: not default_connection_failed

- name: Install shared configuration
  import_playbook: shared_install.yml
  vars:
    runnig_hosts: raspberry-lutece
    open_dns_port: "yes"

- hosts: raspberry-lutece
  become: true
  remote_user: "{{ server_user.name }}"
  vars_files:
    - ./secrets.yml

  roles:
    - role: disks_setup
      disks:
        - mount_point: /media/Lutece_1
          disk_label: Lutece_1

    - role: haelle.certbot
      vars:
        certbot_install_method: snap
        certbot_create_if_missing: 'yes'
        certbot_create_method: standalone
        certbot_admin_email: "{{ certbot_email }}"
        certbot_certs:
          - domains:
            - "trou-noir.alxs.fr"
      tags:
        - certbot
        - pi-hole

    - role: pi_hole
      vars:
        docker_user: "{{ server_user.name }}"
      tags: pi-hole
