---
- hosts: raspberry-local
  remote_user: pi # default password is 'raspberry'
  become: true
  vars:
    mount_point: /media/data
    disk_uuid: f3ebf1cd-ce7f-4633-ac6d-3b5945ff85e4
  vars_files:
    - ./secrets.yml

  roles:
    - role: pre-install
      tags: pre-install

    - role: singleplatform-eng.users
      users:
        - username: pi
          name: pi
          groups: ['sudo', 'www-data']
          password: "{{ pi_password }}"
          ssh_key:
            - "{{ pi_ssh_key }}"
      tags: users

    - role: haelle.vimrc
      tags: vim

    - role : haelle.oh_my_zsh
      users:
        - pi
      tags: zsh

    - role: elboletaire.transmission
      transmission_user: pi
      transmission_password: "{{ tranmission_password }}"
      transmission_rpc_auth_required: true
      transmission_download_dir: "{{ mount_point }}/downloads"
      transmission_incomplete_dir: "{{ mount_point }}/.incomplete"
      transmission_watch_dir: "{{ mount_point }}/torrents"
      transmission_rpc_whitelist_enabled: false
      tags: transmission

    - role: plex
      tags: plex

    - role: php
      tags: nextcloud

    - role: aalaesar.install_nextcloud
      php_version: "7.3"
      php_custom: yes
      php_ver: "{{ php_version }}"
      php_dir: "/etc/php/{{ php_version }}"
      php_bin: "php-fpm{{ php_version }}"
      php_pkg_apcu: "php-apcu"
      php_pkg_spe:
        - "php{{ php_version }}-imap"
        - "php{{ php_version }}-imagick"
        - "php{{ php_version }}-xml"
        - "php{{ php_version }}-zip"
        - "php{{ php_version }}-mbstring"
        - "php-redis"
      php_socket: "/var/run/php/php{{ php_version }}-fpm.sock"
      nextcloud_trusted_domain:
        - cloud.alxs.fr
      nextcloud_websrv: nginx
      nextcloud_data_dir: "{{ mount_point }}/nextcloud"
      nextcloud_admin_pwd: "{{ nextcloud_admin_password }}"
      nextcloud_db_backend: pgsql
      nextcloud_db_pwd: "{{ nextcloud_db_password }}"
      tags: nextcloud

    - role: post-install
      plex_server_name: plex.alxs.fr
      transmission_server_name: transmission.alxs.fr
      certbot_admin_email: "{{ certbot_email }}"
      domains_to_cert:
        - plex.alxs.fr
        - transmission.alxs.fr
        - cloud.alxs.fr
      tags: post-install
