---
- hosts: raspberry
  remote_user: pi # default password is 'raspberry'
  become: true
  vars:
    server_ip: "{{ ansible_default_ipv4.address }}"
    mount_point: /media/data
    # not sure what IP is needed here
    nfs_allowed_ips: 192.168.1.0/24
  vars_files:
    - ./secrets.yml

  roles:
    - role: packages
      tags: base

    - role: singleplatform-eng.users
      users:
        - username: pi
          name: pi
          groups: ['sudo']
          password: "{{ pi_password }}"
          ssh_key:
            - "{{ pi_ssh_key }}"
      tags: users

    - role: viasite-ansible.zsh
      zsh_user: pi
      tags: zsh

    - role: mrlesmithjr.mdadm
      mdadm_arrays:
        - name: 'md0'
          devices:
            - '/dev/sda'
            - '/dev/sdb'
          filesystem: 'ext4'
          filesystem_opts: ''
          level: '1'
          mountpoint: "{{ mount_point }}"
          state: 'present'
          opts: 'noatime'
      tags: mdadm

    - role: elboletaire.transmission
      transmission_user: pi
      transmission_password: "{{ tranmission_password }}"
      transmission_rpc_auth_required: true
      transmission_download_dir: "{{ mount_point }}/downloads"
      transmission_incomplete_dir: "{{ mount_point }}/.incomplete"
      transmission_watch_dir: "{{ mount_point }}/torrents"
      transmission_rpc_whitelist_enabled: false
      tags: transmission

    - role: plex
      tags: plex

    - role: php
      tags: nextcloud

    - role: aalaesar.install_nextcloud
      php_version: "7.3"
      php_custom: yes
      php_ver: "{{ php_version }}"
      php_dir: "/etc/php/{{ php_version }}"
      php_bin: "php-fpm{{ php_version }}"
      php_pkg_apcu: "php-apcu"
      php_pkg_spe:
        - "php{{ php_version }}-imap"
        - "php{{ php_version }}-imagick"
        - "php{{ php_version }}-xml"
        - "php{{ php_version }}-zip"
        - "php{{ php_version }}-mbstring"
        - "php-redis"
      php_socket: "/var/run/php/php{{ php_version }}-fpm.sock"
      nextcloud_trusted_domain:
        - cloud.alxs.fr
      nextcloud_websrv: nginx
      nextcloud_data_dir: "{{ mount_point }}/nextcloud"
      nextcloud_admin_pwd: "{{ nextcloud_admin_password }}"
      nextcloud_db_backend: pgsql
      nextcloud_db_pwd: "{{ nextcloud_db_password }}"
      tags: nextcloud

    - role: media-server
      plex_server_name: plex.alxs.fr
      transmission_server_name: transmission.alxs.fr
      tags: server-confs
