---
- src: singleplatform-eng.users
  version: v1.2.6
- src: elboletaire.transmission
  version: 2.0.1
- src: aalaesar.install_nextcloud
  version: v1.3.4
- src: haelle.oh_my_zsh
  version: 0.11.0
- src: haelle.vimrc
  version: 0.5.0
- src: haelle.airsonic
  version: 0.3.0
- src: geerlingguy.docker
  version: 2.9.0
# not sure if is useful
# currently not used but maybe needed for docker to work
- src: geerlingguy.pip
  version: 2.0.0
- src: haelle.certbot_ansible
  version: 1.2.0
