---
- src: aalaesar.install_nextcloud
  version: v1.3.4
- src: haelle.oh_my_zsh
  version: 1.0.3
- src: haelle.vimrc
  version: 1.0.2
- src: haelle.airsonic
  version: 0.3.0
- src: geerlingguy.docker
  version: 4.1.3
# not sure if is useful
# currently not used but maybe needed for docker to work
- src: geerlingguy.pip
  version: 2.0.0
- src: haelle.calibre_web_ansible
  version: 1.6.1
- src: nginxinc.nginx
  version: 0.19.2
- src: nginxinc.nginx_config
  version: 0.3.3
  # forked from geerlingguy.certbot
- src: haelle.certbot
  version: 4.0.3
