---
# TODO: make a full reinstall to make it work properly
# it needs the pre-task to create the user and disable the default one

- name: Install shared configuration
  import_playbook: shared_install.yml
  vars:
    runnig_hosts: raspberry-rothomagus

- hosts: raspberry-rothomagus
  remote_user: pi  # default password is 'raspberry'
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - ./secrets.yml

  roles:
    - role: pre-install
      plex_data_mount_point: "{{ disks[0].mount_point }}/plex_data"
      tags: pre-install

    - role: disks_setup
      disks:
      - mount_point: /media/data
        disk_label: Raspbian_1
      - mount_point: /media/raspbian_2
        disk_label: Raspbian_2

    #- role: singleplatform-eng.users
      #users:
        #- username: pi
          #name: pi
          #groups: ['sudo', 'www-data']
          #password: "{{ pi_password }}"
          #ssh_key:
            #- "{{ ssh_key }}"
      #tags: users

    - role: haelle.airsonic
      tags: airsonic

    #- role: elboletaire.transmission
      #transmission_user: pi
      #transmission_password: "{{ tranmission_password }}"
      #transmission_rpc_auth_required: true
      #transmission_download_dir: "{{ disks[0].mount_point }}/downloads"
      #transmission_incomplete_dir: "{{ disks[0].mount_point }}/.incomplete"
      #transmission_watch_dir: "{{ disks[0].mount_point }}/torrents"
      #transmission_rpc_whitelist_enabled: false
      #transmission_peer_port: 51413
      #transmission_port_forwarding_enabled: true
      #tags: transmission

    - role: php
      tags: nextcloud

    - role: aalaesar.install_nextcloud
      php_version: "7.3"
      php_custom: 'yes'
      php_ver: "{{ php_version }}"
      php_dir: "/etc/php/{{ php_version }}"
      php_bin: "php-fpm{{ php_version }}"
      php_pkg_apcu: "php-apcu"
      php_pkg_spe:
        - "php{{ php_version }}-imap"
        - "php{{ php_version }}-imagick"
        - "php{{ php_version }}-xml"
        - "php{{ php_version }}-zip"
        - "php{{ php_version }}-mbstring"
        - "php{{ php_version }}-bcmath"
        - "php{{ php_version }}-gmp"
        - "php-redis"
      # Spécifier PHP version peut casser (non ?)
      php_socket: "/var/run/php/php{{ php_version }}-fpm.sock"
      nextcloud_trusted_domain:
        - cloud.alxs.fr
        - nuage.alxs.fr
      nextcloud_websrv: nginx
      nextcloud_data_dir: "{{ disks[0].mount_point }}/nextcloud"
      nextcloud_admin_pwd: "{{ nextcloud_admin_password }}"
      nextcloud_db_backend: pgsql
      nextcloud_db_pwd: "{{ nextcloud_db_password }}"
      nextcloud_hsts: "max-age=15768000; includeSubDomains; preload"
      tags: nextcloud

    - role: booksonic
      tags:
        - docker
        - booksonic

    - role: post-install
      plex_server_name: plex.alxs.fr
      transmission_server_name: transmission.alxs.fr
      airsonic_server_name: music.alxs.fr
      booksonic_server_name: audiobook.alxs.fr
      tags: post-install

    - role: haelle.certbot_ansible
      certbot_admin_email: "{{ certbot_email }}"
      domains_to_cert:
        - plex.alxs.fr
        #- transmission.alxs.fr
        - cloud.alxs.fr
        - nuage.alxs.fr
        - music.alxs.fr
        - audiobook.alxs.fr
      tags: certbot
