---
# TODO: make a full reinstall to make it work properly
# it needs the pre-task to create the user and disable the default one

- name: Install shared configuration
  import_playbook: shared_install.yml
  vars:
    runnig_hosts: vps-treola

- hosts: vps-treola
  become: true
  remote_user: "{{ server_user.name }}"
  vars:
    nextcloud_dir: "/home/{{ server_user.name }}/Nextcloud/"
  vars_files:
    - ./secrets.yml

  roles:
    - role: chloegaster.fr
      chloegaster:
        certbot_email: "{{ certbot_email }}"
        fqdn: chloegaster.fr
      tags: chloegaster

    - role: haelle.calibre_web_ansible
      calibre_web:
        name: alexandrie
        port: 8086
        fqdn: alexandrie.alxs.fr
        db_symlink_path: '{{ nextcloud_dir }}Livres_numériques/calibre-web-configs/alexandrie-app.db'
        certbot_email: "{{ certbot_email }}"
      tags:
        - alexandrie
        - calibre

    - role: haelle.calibre_web_ansible
      calibre_web:
        name: bazar
        port: 8087
        fqdn: bazar.alxs.fr
        db_symlink_path: '{{ nextcloud_dir }}Livres_numériques/calibre-web-configs/bazar-app.db'
        certbot_email: "{{ certbot_email }}"
      tags:
        - bazar
        - calibre

    - role: haelle.calibre_web_ansible
      calibre_web:
        name: comics
        port: 8088
        fqdn: comics.alxs.fr
        db_symlink_path: '{{ nextcloud_dir }}Livres_numériques/calibre-web-configs/comics-app.db'
        certbot_email: "{{ certbot_email }}"
      tags:
        - comics
        - calibre
