---
- name: Install desktop packages
  apt:
    pkg:
      - chromium-browser
      - cloc
      - cowsay
      - copyq
      - curl
      - docker
      - docker-compose
      - direnv
      - finger
      - gnome-tweaks
      - htop
      - magic-wormhole
      - mmv
      - mosh
      - peek
      - snapd
      - steam
      - telnet
      - tree
      - whois
    state: latest

- name: Ensure ~/.ssh exists
  file:
    path: ~/.ssh
    state: directory
  become_user: "{{ server_user.name }}"

- name: Ensure ~/.ssh/config exists
  file:
    path: ~/.ssh/config
    state: touch
  become_user: "{{ server_user.name }}"

- name: SSH default config
  blockinfile:
    path: "/home/{{ server_user.name }}/.ssh/config"
    block: |
      Host *
      ServerAliveInterval 100
      ServerAliveCountMax 2
      ForwardAgent yes
      UserKnownHostsFile ~/.ssh/known_hosts
      IdentityFile ~/.ssh/id_rsa
      #StrictHostKeyChecking no
    insertbefore: EOF
    marker: "# {mark} ANSIBLE BLOCK: ssh config"

- name: Add KeepassXC official repository
  apt_repository:
    repo: ppa:phoerious/keepassxc
    state: present
    update_cache: "yes"
  tags:
    - keepass
    - keepass-xc

- name: Add Unity apt key
  apt_key:
    url: https://hub.unity3d.com/linux/keys/public
    state: present

# Currently for Ubuntu 22.04 it needs this package to be installed
# http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
- name: Add UnityHub official repository
  apt_repository:
    repo: deb https://hub.unity3d.com/linux/repos/deb stable main
    state: present
    update_cache: "yes"

- name: Add Nemo Seahorse repository
  apt_repository:
    repo: ppa:wasta-linux/cinnamon-testing
    state: present
    update_cache: "yes"

- name: Install desktop packages
  apt:
    pkg:
      - calibre
      - chrome-gnome-shell
      - dotnet6
      - exfat-fuse
      - gimp
      - ghostwriter
      - gnome-shell-pomodoro
      - gnome-tweaks
      - keepassxc
      - libssl-dev
      - libyaml-dev
      - meld
      - nautilus-nextcloud
      - nemo
      - nemo-nextcloud
      - nemo-seahorse
      - seahorse-nautilus
      - steam
      - unityhub
      - variety
      - vlc
      - xournal
    state: latest
    update_cache: yes

- name: Snap packages
  snap:
    name:
      - pycharm-community
      - slack
      - skype
      - insomnia
      - gitkraken
      - hey-mail
    classic: "yes"
  tags: pycharm

- name: Rider with specific version
  snap:
    name: rider
    classic: "yes"
    channel: "2019.2/stable"
  tags: rider

- name: Install Fusuma gestures
  include: fusuma.yml
