---
- name: Auto start SSH
  service:
    name: ssh
    enabled: 'yes'

- name: Disable GUI at boot time
  command: raspi-config nonint do_boot_behaviour B1
  become: true

- name: Install mandatory packages
  apt:
    name:
      - vim
      - software-properties-common
      - build-essential
      - powerline
      - fonts-powerline
      - silversearcher-ag

- name: Setup fstab & disks rights
  include: auto_mount_disks.yml
  with_items: '{{ disks }}'
  tags: fstab
