---
- name: Install git
  apt:
    name:
      - git
      - git-flow
    state: latest

- name: Copy gitignore file
  template:
    src: ./gitconfig.j2
    dest: /home/{{ server_user.name}}/.gitconfig
    mode: '0644'
  become_user: "{{ server_user.name }}"
