---
- name: Install & configure Ag SilverSearch
  include: ag_setup.yml
  tags:
    - ag
    - silversearch

- name: Install & configure Git
  include: git_setup.yml
  tags: git

- name: Install & configure Tmux
  include: tmux_setup.yml
  tags: tmux

- name: Install Ruby for lolcat
  apt:
    pkg: ruby

- name: Install lolcat
  community.general.gem:
    name: lolcat
    state: present
