---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    validate_certs: no

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    copy: no

- name: rename source folder
  shell: mv /var/www/wordpress /var/www/chloegaster.fr
  ignore_errors: yes

- name: delete source folder if already exists
  file:
    path: /var/www/wordpress
    state: absent

- name: set permissions to folder
  file:
    path: /var/www/chloegaster.fr
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes

- name: retrieve new wordpress keys and salts
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    method: GET
    return_content: yes
  register: wp_salt
  tags: salt

- name: copy template wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/chloegaster.fr/wp-config.php
    owner: www-data
    group: www-data
    mode: 0755
  tags: salt
