- name: Copy Nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/reverse_proxy.conf
    mode: 0644

- name: symlink to site enabled
  file:
    src: /etc/nginx/sites-available/reverse_proxy.conf
    path: /etc/nginx/sites-enabled/reverse_proxy.conf
    state: link
