---
# This role "successfully" install Docker/docker-compose for:
# [X] Raspberry Pi 4 with Ubuntu 20.04
# [ ] Raspberry Pi 3 with Raspbian X
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - libffi-dev
      - libssl-dev
      - software-properties-common
    state: present

- name: Install PIP
  include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker

- name: Install Docker
  include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose: true

- name: Install docker-compose from pip3
  become: true
  shell: pip3 install docker-compose
  when: # Raspberry Pi 3 with Debian Stretch
    - ansible_architecture == "armv7l"
    - ansible_distribution == "Debian"
    - ansible_distribution_version == "9"

- name: Install docker-compose from apt
  apt:
    name:
      - docker-compose
    state: present
  when: # Raspberry Pi 4 with Ubuntu Focal
    - ansible_architecture == "aarch64"
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "20.04"
