---
default_user: pi
hostname: rothomagus
static_ip: 192.168.1.3
# $ arch => armv7l
docker_apt_arch: armhf
server_user:
  name: pi
  group: pi
  fullname: Pi
  email: '{{ email }}'
  ssh_key: '{{ ssh_key }}'
