---
default_user: ubuntu
hostname: lutece
# $ arch => aarch64
docker_apt_arch: arm64
server_user:
  name: '{{ name }}'
  group: '{{ group }}'
  fullname: '{{ fullname }}'
  email: '{{ email }}'
  ssh_key: '{{ ssh_key }}'
docker_compose_url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-armv7
