---
- name: Install dependencies
  apt:
    name: apt-transport-https
    state: present

- name: Add Sury.org apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add Sury.org PHP 7.1 repo
  apt_repository:
    repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
    state: present
  register: sury_org_repo_added

- name: Update
  apt:
    update_cache: yes
  when: sury_org_repo_added.changed
