---
- name: Install Certbot
  apt:
    name:
      - certbot
      - python-certbot-nginx

- name: issue certificates for each domains
  include: issue_certificates.yml
  with_items: "{{ domains_to_cert }}"
