---
- name: Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh
  tags: ssh

- name: Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh
  tags: ssh

- name: Passwordless users
  lineinfile:
    path: /etc/sudoers
    regexp: '\%sudo.+ALL=\(ALL:ALL\).+ALL'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD: ALL'
    state: present
  tags: ssh
