---
- name: Nginx confs
  include: nginx.yml
  tags: cloud-nginx

- name: Open ports in UFW
  include: ufw.yml
  tags: ufw

- name: Nextcloud
  include: nextcloud.yml
  tags: nextcloud

- name: Disallow password login
  include: disallow_ssh.yml
  tags: ssh
