---
- name: Add X-Frame-Options SAMEORIGIN
  lineinfile:
    path: /etc/nginx/sites-available/nc_cloud.alxs.fr.cnf
    line: '    add_header X-Frame-Options "SAMEORIGIN";'
    insertbefore: 'X-Content-Type-Options'
    firstmatch: 'yes'
    state: present
  tags:
    - nginx
    - nextcloud
    - nextcloud-frame-options
  notify: reload nginx

- name: Install SVG dependency
  apt:
    name: libmagickcore-6.q16-3-extra
    state: present

# WARNING it depends on rothomagus.yml php_version
- name: Remove PHP memory limit (cli)
  lineinfile:
    path: /etc/php/7.3/cli/php.ini
    regexp: '^memory_limit'
    line: 'memory_limit = -1'
  notify: reload php

- name: Remove PHP memory limit (fpm)
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    regexp: '^memory_limit'
    line: 'memory_limit = -1'
  notify: reload php

- name: Enable PHP APCU (cli)
  lineinfile:
    path: /etc/php/7.3/cli/php.ini
    line: 'apc.enable_cli = 1'
    insertafter: EOF
  notify: reload php

- name: Enable PHP APCU (fpm)
  lineinfile:
    path: /etc/php/7.3/fpm/php.ini
    line: 'apc.enable_cli = 1'
    insertafter: EOF
  notify: reload php

- name: Use system env variables (fpm)
  lineinfile:
    path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    regexp: ';clear_env = no'
    line: 'clear_env = no'
  notify: reload php

- name: Add default_phone_region to nextcloud config
  lineinfile:
    path: "/opt/nextcloud/config/config.php"
    line: "'default_phone_region' => 'FR',"
    insertbefore: '^maintenance'
  notifiy: reload php
