---
- name: Copy Nginx conf Transmission
  template:
    src: transmission.conf.j2
    dest: /etc/nginx/sites-available/transmission.conf
    mode: 0644
  notify: reload nginx
  tags: transmission

- name: symlink to site enabled Transmission
  file:
    src: /etc/nginx/sites-available/transmission.conf
    path: /etc/nginx/sites-enabled/transmission.conf
    state: link
  notify: reload nginx
  tags: transmission

- name: Copy Nginx conf Plex
  template:
    src: plex.conf.j2
    dest: /etc/nginx/sites-available/plex.conf
    mode: 0644
  notify: reload nginx
  tags: plex

- name: symlink to site enabled Plex
  file:
    src: /etc/nginx/sites-available/plex.conf
    path: /etc/nginx/sites-enabled/plex.conf
    state: link
  notify: reload nginx
  tags: plex

- name: Copy Nginx conf Airsonic
  template:
    src: airsonic.conf.j2
    dest: /etc/nginx/sites-available/airsonic.conf
    mode: 0644
  notify: reload nginx
  tags: airsonic

- name: symlink to site enabled Airsonic
  file:
    src: /etc/nginx/sites-available/airsonic.conf
    path: /etc/nginx/sites-enabled/airsonic.conf
    state: link
  notify: reload nginx
  tags: airsonic
