---
- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Remove TLSv1.0 & TLSv1.1 Nginx support
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'ssl_protocols'
    line: '  ssl_protocols TLSv1.2;'
    state: present
  notify: restart nginx

- name: Disable Ciphers kindness
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: 'ssl_prefer_server_ciphers'
    line: '  ssl_prefer_server_ciphers off;'
    state: present
  notify: restart nginx

- name: Copy Nginx conf Transmission
  template:
    src: transmission.conf.j2
    dest: /etc/nginx/sites-available/transmission.conf
    mode: 0644
    force: no
  notify: reload nginx
  tags: transmission

- name: symlink to site enabled Transmission
  file:
    src: /etc/nginx/sites-available/transmission.conf
    path: /etc/nginx/sites-enabled/transmission.conf
    state: link
  notify: reload nginx
  tags: transmission

- name: Copy Nginx conf Plex
  template:
    src: plex.conf.j2
    dest: /etc/nginx/sites-available/plex.conf
    mode: 0644
    force: no
  notify: reload nginx
  tags: plex

- name: symlink to site enabled Plex
  file:
    src: /etc/nginx/sites-available/plex.conf
    path: /etc/nginx/sites-enabled/plex.conf
    state: link
  notify: reload nginx
  tags: plex

- name: Copy Nginx conf Airsonic
  template:
    src: airsonic.conf.j2
    dest: /etc/nginx/sites-available/airsonic.conf
    mode: 0644
    force: no
  notify: reload nginx
  tags: airsonic

- name: symlink to site enabled Airsonic
  file:
    src: /etc/nginx/sites-available/airsonic.conf
    path: /etc/nginx/sites-enabled/airsonic.conf
    state: link
  notify: reload nginx
  tags: airsonic

- name: Copy Nginx conf Booksonic
  template:
    src: booksonic.conf.j2
    dest: /etc/nginx/sites-available/booksonic.conf
    mode: 0644
    force: no
  notify: reload nginx
  tags: booksonic

- name: symlink to site enabled Booksonic
  file:
    src: /etc/nginx/sites-available/booksonic.conf
    path: /etc/nginx/sites-enabled/booksonic.conf
    state: link
  notify: reload nginx
  tags: booksonic
