---
- name: create destination directory
  file:
    path: /mnt/data/plex_data
    state: directory
    owner: plex
    group: plex

- name: backup Plex config
  shell: mv /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server.backup
  become: true

- name: copy current config to data partition
  shell: cp -r /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server.backup {{ mount_point }}/plex_data
  become: true

# /!\
# TODO: this is not tested
- name: change rights for plex directory
  file:
    path: "{{ mount_point }}/plex_data/Plex\ Media\ Server"
    owner: plex
    group: plex
    state: directory
    mode: 0755

- name: create symlink
  file:
    src: "{{ mount_point }}/plex_data/Plex\ Media\ Server"
    path: "/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server"
    owner: plex
    group: plex
    state: link
