---
- name: Install UFW
  apt:
    name: ufw
    state: latest

- name: Support IPv6
  lineinfile:
    path: /etc/default/ufw
    line: "IPV6=yes"
    state: present

- name: Configure ufw defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Configure basic ufw rules
  ufw:
    rule:  allow
    port:  "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { port: '22', proto: 'tcp' }
    - { port: '21', proto: 'tcp' }
    - { port: '80', proto: 'tcp' }
    - { port: '443', proto: 'tcp' }
  ignore_errors: true

- name: Allow NFS in UFW (only work if nfs in /etc/services)
  ufw:
    rule: allow
    name: nfs
  tags: nfs
  ignore_errors: true

- name: Allow Transmission in UFW
  ufw:
    rule: allow
    port: 9091
  ignore_errors: true
  tags: transmission

- name: Allow Transmission in UFW
  ufw:
    rule: allow
    port: 51413
  ignore_errors: true
  tags: transmission

- name: Allow Plex in UFW
  ufw:
    rule: allow
    port: 32400
  ignore_errors: true
  tags: plex
