---
- name: Check if CSFD.bundle exists
  stat:
    path: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/CSFD.bundle"
  register: csfd_bundle

- name: Create /tmp/csfd-plex
  file:
    path: /tmp/csfd-plex
    state: directory

- name: Unarchive csfd-plex
  unarchive:
    src: https://github.com/misko/csfd-plex/archive/master.zip
    dest: /tmp/csfd-plex
    remote_src: yes
  when: csfd_bundle.stat.exists == False

- name: Check if /tmp/csfd-plex/CSFD.bundle exists
  stat:
    path: /tmp/csfd-plex/csfd-plex-master/CSFD.bundle
  register: tmp_csfd_bundle

- name: Move CSFD.bundle in place
  command: mv /tmp/csfd-plex/csfd-plex-master/CSFD.bundle "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/"
  when: tmp_csfd_bundle.stat.exists == True

- name: Remove /tmp/csfd-plex
  file:
    path: /tmp/csfd-plex
    state: absent
