---
- name: Set Git name
  set_fact:
    plex_git: "{{ plex_root }}/pms-docker"

- name: Create mandatory directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ server_user.name }}"
    group: "{{ server_user.name }}"
    mode: u=rwX,g=rX,o=rX
  loop:
    - "{{ plex_root }}"
    - "{{ plex_git }}"
    - "{{ plex_database }}"
    - "{{ plex_transcode_temp_dir }}"
    - "{{ plex_medias }}"

- name: Clone repository
  git:
    repo: https://github.com/plexinc/pms-docker.git
    dest: "{{ plex_git }}"

- name: Getent get '{{ server_user.name }}' UID/GID
  getent:
    database: passwd
    key: "{{ server_user.name }}"

- name: get '{{ server_user.name }}' UID
  set_fact:
    plex_uid: "{{ getent_passwd[server_user.name].1 }}"

- name: get '{{ server_user.name }}' GID
  set_fact:
    plex_gid: "{{ getent_passwd[server_user.name].2 }}"

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ plex_git }}/docker-compose.yml"
    mode: 0644
    force: "yes"

- name: Create and start services
  become: "yes"
  community.general.docker_compose:
    project_src: "{{ plex_git }}"

- name: Copy Nginx conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/plex.conf
    mode: 0644

- name: symlink to site enabled
  file:
    src: /etc/nginx/sites-available/plex.conf
    path: /etc/nginx/sites-enabled/plex.conf
    state: link
