---
- name: create destination directory
  file:
    path: "{{ plex_data_mount_point}}"
    state: directory
    owner: plex
    group: plex

- name: stop Plex
  service:
    name: plexmediaserver
    state: stopped

- name: copy current config to data partition
  shell: cp -r /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server {{ plex_data_mount_point }}
  become: true

- name: backup Plex files
  shell: mv /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server.backup
  become: true

- name: change rights for plex directory
  file:
    path: "{{ plex_data_mount_point }}"
    owner: plex
    group: plex
    state: directory
    mode: u=rwX,g=rX,o=rX
    recurse: 'yes'

- name: create symlink
  file:
    src: "{{ plex_data_mount_point }}/Plex\ Media\ Server"
    path: "/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server"
    owner: plex
    group: plex
    state: link
  notify: restart plex
